from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Iterable, Literal, Mapping, Sequence

import numpy as np

from .interfaces import CandidateGenerator, MultiVectorSource, Reranker
from .representation import Representation

class IncompatibleIndexError(ValueError): ...
class IncompatibleQueryError(ValueError): ...

class Feature:
    def __init__(
        self,
        representation: Representation,
        value: Any = None,
        *,
        provider: Callable[[], Any] | None = None,
    ) -> None: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def value(self) -> Any: ...

class Query:
    def __init__(self, text: str, **features: Feature) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def features(self) -> dict[str, Feature]: ...
    def feature(self, name: str, representation: Representation) -> Any: ...

class Candidate:
    def __init__(
        self,
        corpus: str,
        document_id: str,
        gather_score: float,
        gather_rank: int,
        provenance: str,
    ) -> None: ...
    @property
    def corpus(self) -> str: ...
    @property
    def document_id(self) -> str: ...
    @property
    def gather_score(self) -> float: ...
    @property
    def gather_rank(self) -> int: ...
    @property
    def provenance(self) -> str: ...

class Gathered:
    def __init__(self, candidates: Iterable[Candidate], as_of: datetime) -> None: ...
    @property
    def candidates(self) -> tuple[Candidate, ...]: ...
    @property
    def as_of(self) -> datetime: ...

class Scored:
    def __init__(self, scores: Iterable[float | None], as_of: datetime) -> None: ...
    @property
    def scores(self) -> list[float | None]: ...
    @property
    def as_of(self) -> datetime: ...

class ResourceBudget:
    def __init__(
        self,
        *,
        max_batch_tokens: int = 131_072,
        max_documents_per_batch: int = 256,
        threads: int | None = None,
    ) -> None: ...
    @property
    def max_batch_tokens(self) -> int: ...
    @property
    def max_documents_per_batch(self) -> int: ...
    @property
    def threads(self) -> int | None: ...

class RankedDocument:
    @property
    def corpus(self) -> str: ...
    @property
    def document_id(self) -> str: ...
    @property
    def score(self) -> float: ...
    @property
    def rank(self) -> int: ...

class SearchTimings:
    @property
    def gather_seconds(self) -> float: ...
    @property
    def rerank_seconds(self) -> float: ...
    @property
    def total_seconds(self) -> float: ...

class SearchResult:
    @property
    def documents(self) -> tuple[RankedDocument, ...]: ...
    @property
    def candidates(self) -> tuple[Candidate, ...]: ...
    @property
    def scores(self) -> list[float | None]: ...
    @property
    def as_of(self) -> datetime: ...
    @property
    def timings(self) -> SearchTimings: ...
    @property
    def diagnostics(self) -> dict[str, Any]: ...

class SearchPipeline:
    def __init__(
        self,
        gatherer: CandidateGenerator,
        reranker: Reranker | MaxSimReranker | None = None,
    ) -> None: ...
    def search(
        self,
        query: Query | str,
        *,
        gather_limit: int,
        limit: int,
        subset: Mapping[str, Iterable[str]] | None = None,
        budget: ResourceBudget | None = None,
    ) -> SearchResult: ...

class MaxSimReranker:
    def __init__(
        self,
        sources: Iterable[VectorStore | MultiVectorSource],
        *,
        feature: str = "multi_vector",
    ) -> None: ...
    @property
    def sources(self) -> tuple[VectorStore | MultiVectorSource, ...]: ...
    @property
    def requires(self) -> dict[str, Representation]: ...
    @property
    def score_semantics(self) -> str: ...
    @property
    def feature(self) -> str: ...
    def rerank(
        self, query: Query, candidates: Sequence[Candidate], *, budget: ResourceBudget
    ) -> Scored: ...

class StoreView:
    @property
    def as_of(self) -> datetime: ...
    @property
    def commit(self) -> int: ...
    @property
    def document_ids(self) -> list[str]: ...
    def __contains__(self, document_id: object) -> bool: ...
    def document_lengths(self, document_ids: Iterable[str]) -> dict[str, int]: ...
    def fetch(
        self, document_ids: Iterable[str], *, threads: int | None = None
    ) -> tuple[np.ndarray, np.ndarray]: ...

class VectorStore:
    def __init__(self, path: str | Path) -> None: ...
    @property
    def path(self) -> Path: ...
    @property
    def corpus(self) -> str: ...
    @property
    def encoding(self) -> Literal["float32", "int8"]: ...
    @property
    def score_semantics(self) -> str: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def dimension(self) -> int: ...
    def view(self) -> StoreView: ...

class VectorStoreWriter:
    def __init__(self, path: str | Path) -> None: ...
    @staticmethod
    def create(
        path: str | Path,
        corpus: str,
        representation: Representation,
        *,
        encoding: Literal["float32", "int8"] = "float32",
    ) -> VectorStoreWriter: ...
    @property
    def corpus(self) -> str: ...
    def append(
        self,
        document_ids: Iterable[str],
        embeddings: np.ndarray,
        document_lengths: np.ndarray | Sequence[int],
        *,
        threads: int | None = None,
    ) -> None: ...
    def delete(self, document_ids: Iterable[str]) -> int: ...
    def compact(self) -> None: ...
    def commit(self) -> datetime: ...

def maxsim_scores_packed(
    query: np.ndarray,
    documents: np.ndarray,
    document_lengths: np.ndarray,
    *,
    max_batch_tokens: int | None = None,
    threads: int | None = None,
) -> np.ndarray: ...
def _check_representation(representation: Representation) -> None: ...
def _assert_representations_compatible(left: Representation, right: Representation) -> None: ...
