from pathlib import Path
from typing import Any, Callable, ClassVar, Sequence

import numpy as np

from .interfaces import CandidateGenerator, MultiVectorSource, Reranker
from .manifest import CorpusManifest, Representation

class IncompatibleIndexError(ValueError): ...
class IncompatibleQueryError(ValueError): ...

class Feature:
    def __init__(
        self,
        representation: Representation,
        value: Any = None,
        *,
        provider: Callable[[], Any] | None = None,
    ) -> None: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def value(self) -> Any: ...

class Query:
    def __init__(self, text: str, **features: Feature) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def features(self) -> dict[str, Feature]: ...
    def feature(self, name: str, representation: Representation) -> Any: ...

class Candidate:
    def __init__(
        self, document_id: int, gather_score: float, gather_rank: int, provenance: str
    ) -> None: ...
    @property
    def document_id(self) -> int: ...
    @property
    def gather_score(self) -> float: ...
    @property
    def gather_rank(self) -> int: ...
    @property
    def provenance(self) -> str: ...

class Score:
    def __init__(self, document_id: int, value: float) -> None: ...
    @property
    def document_id(self) -> int: ...
    @property
    def value(self) -> float: ...

class ResourceBudget:
    def __init__(
        self,
        *,
        max_batch_tokens: int = 131_072,
        max_documents_per_batch: int = 256,
        threads: int | None = None,
    ) -> None: ...
    @property
    def max_batch_tokens(self) -> int: ...
    @property
    def max_documents_per_batch(self) -> int: ...
    @property
    def threads(self) -> int | None: ...

class RankedDocument:
    @property
    def document_id(self) -> int: ...
    @property
    def score(self) -> float: ...
    @property
    def rank(self) -> int: ...

class SearchTimings:
    @property
    def gather_seconds(self) -> float: ...
    @property
    def rerank_seconds(self) -> float: ...
    @property
    def total_seconds(self) -> float: ...

class SearchResult:
    @property
    def documents(self) -> tuple[RankedDocument, ...]: ...
    @property
    def candidates(self) -> tuple[Candidate, ...]: ...
    @property
    def scores(self) -> tuple[Score, ...]: ...
    @property
    def timings(self) -> SearchTimings: ...
    @property
    def diagnostics(self) -> dict[str, Any]: ...

class SearchPipeline:
    def __init__(
        self, gatherer: CandidateGenerator, reranker: Reranker | MaxSimReranker | None = None
    ) -> None: ...
    @property
    def gatherer(self) -> CandidateGenerator: ...
    @property
    def reranker(self) -> Reranker | MaxSimReranker | None: ...
    def search(
        self,
        query: Query | str,
        *,
        gather_limit: int,
        limit: int,
        subset: np.ndarray | Sequence[int] | None = None,
        budget: ResourceBudget | None = None,
    ) -> SearchResult: ...

class MaxSimReranker:
    def __init__(
        self,
        source: MultiVectorSource,
        corpus: CorpusManifest,
        *,
        feature: str = "multi_vector",
    ) -> None: ...
    @property
    def source(self) -> MultiVectorSource: ...
    @property
    def corpus(self) -> CorpusManifest: ...
    @property
    def requires(self) -> dict[str, Representation]: ...
    @property
    def score_semantics(self) -> str: ...
    @property
    def feature(self) -> str: ...
    def rerank(
        self, query: Query, candidates: Sequence[Candidate], *, budget: ResourceBudget
    ) -> tuple[Score, ...]: ...

class VectorStore:
    format: ClassVar[str]
    score_semantics: ClassVar[str]
    @property
    def path(self) -> Path: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def dimension(self) -> int: ...
    @property
    def document_count(self) -> int: ...
    @property
    def token_count(self) -> int: ...
    def document_lengths(self, document_ids: Sequence[int]) -> dict[int, int]: ...
    def fetch(
        self, document_ids: Sequence[int], *, threads: int | None = None
    ) -> tuple[np.ndarray, np.ndarray]: ...
    def append(
        self, embeddings: np.ndarray, document_lengths: np.ndarray, *, threads: int | None = None
    ) -> None: ...
    def delete(self, document_ids: Sequence[int]) -> None: ...

class Float32VectorStore(VectorStore):
    def __init__(self, path: str | Path) -> None: ...
    @classmethod
    def create(
        cls,
        path: str | Path,
        embeddings: np.ndarray,
        document_lengths: np.ndarray,
        representation: Representation,
        *,
        threads: int | None = None,
    ) -> Float32VectorStore: ...

class Int8VectorStore(VectorStore):
    def __init__(self, path: str | Path) -> None: ...
    @classmethod
    def create(
        cls,
        path: str | Path,
        embeddings: np.ndarray,
        document_lengths: np.ndarray,
        representation: Representation,
        *,
        threads: int | None = None,
    ) -> Int8VectorStore: ...

def open_vector_store(path: str | Path) -> VectorStore: ...
def maxsim_scores_packed(
    query: np.ndarray,
    documents: np.ndarray,
    document_lengths: np.ndarray,
    *,
    max_batch_tokens: int | None = None,
    threads: int | None = None,
) -> np.ndarray: ...
def document_ids_digest(document_ids: Sequence[str]) -> str: ...
def _check_corpus_manifest(manifest: CorpusManifest) -> None: ...
def _check_representation(representation: Representation) -> None: ...
def _assert_corpora_compatible(left: CorpusManifest, right: CorpusManifest) -> None: ...
def _assert_representations_compatible(left: Representation, right: Representation) -> None: ...
