from pathlib import Path
from typing import Any, Callable, ClassVar, Iterable, Mapping, Sequence

import numpy as np

from .interfaces import CandidateGenerator, Live, MultiVectorSource, Reranker
from .manifest import CorpusManifest, Representation

class IncompatibleIndexError(ValueError): ...
class IncompatibleQueryError(ValueError): ...

class Segment:
    def __init__(
        self,
        corpus_id: str,
        corpus_version: str,
        document_ids: Iterable[str],
        *,
        generation: int = 0,
    ) -> None: ...
    @classmethod
    def from_manifest(cls, manifest: CorpusManifest, document_ids: Iterable[str]) -> Segment: ...
    @property
    def manifest(self) -> CorpusManifest: ...
    @property
    def corpus_id(self) -> str: ...
    @property
    def generation(self) -> int: ...
    @property
    def document_ids(self) -> list[str]: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, external: object) -> bool: ...
    def internal(self, external: str) -> int: ...
    def external(self, internal: int) -> str: ...
    def to_internal(self, external_ids: Iterable[str]) -> np.ndarray: ...
    def to_external(self, internal_ids: Sequence[int] | np.ndarray) -> list[str]: ...
    def appended(self, document_ids: Iterable[str]) -> Segment: ...
    def deleted(self, document_ids: Iterable[str]) -> Segment: ...

class Feature:
    def __init__(
        self,
        representation: Representation,
        value: Any = None,
        *,
        provider: Callable[[], Any] | None = None,
    ) -> None: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def value(self) -> Any: ...

class Query:
    def __init__(self, text: str, **features: Feature) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def features(self) -> dict[str, Feature]: ...
    def feature(self, name: str, representation: Representation) -> Any: ...

class Candidate:
    def __init__(
        self,
        segment: Segment,
        document_id: int,
        gather_score: float,
        gather_rank: int,
        provenance: str,
    ) -> None: ...
    @property
    def segment(self) -> Segment: ...
    @property
    def document_id(self) -> int: ...
    @property
    def external_id(self) -> str | None: ...
    @property
    def gather_score(self) -> float: ...
    @property
    def gather_rank(self) -> int: ...
    @property
    def provenance(self) -> str: ...

class ResourceBudget:
    def __init__(
        self,
        *,
        max_batch_tokens: int = 131_072,
        max_documents_per_batch: int = 256,
        threads: int | None = None,
    ) -> None: ...
    @property
    def max_batch_tokens(self) -> int: ...
    @property
    def max_documents_per_batch(self) -> int: ...
    @property
    def threads(self) -> int | None: ...

class RankedDocument:
    @property
    def segment(self) -> Segment: ...
    @property
    def corpus_id(self) -> str: ...
    @property
    def document_id(self) -> int: ...
    @property
    def external_id(self) -> str: ...
    @property
    def score(self) -> float: ...
    @property
    def rank(self) -> int: ...

class SearchTimings:
    @property
    def gather_seconds(self) -> float: ...
    @property
    def rerank_seconds(self) -> float: ...
    @property
    def total_seconds(self) -> float: ...

class SearchResult:
    @property
    def documents(self) -> tuple[RankedDocument, ...]: ...
    @property
    def candidates(self) -> tuple[Candidate, ...]: ...
    @property
    def scores(self) -> np.ndarray: ...
    @property
    def timings(self) -> SearchTimings: ...
    @property
    def diagnostics(self) -> dict[str, Any]: ...

class SearchPipeline:
    def __init__(
        self,
        gatherer: CandidateGenerator | Live[CandidateGenerator],
        reranker: Reranker | Live[Reranker] | MaxSimReranker | None = None,
    ) -> None: ...
    def freeze(self) -> SearchPipeline: ...
    def search(
        self,
        query: Query | str,
        *,
        gather_limit: int,
        limit: int,
        subset: Mapping[str, np.ndarray | Sequence[int]] | None = None,
        budget: ResourceBudget | None = None,
    ) -> SearchResult: ...

class MaxSimReranker:
    def __init__(
        self,
        sources: Iterable[VectorStore | StoreSnapshot | MultiVectorSource | Live[MultiVectorSource]],
        *,
        feature: str = "multi_vector",
    ) -> None: ...
    @property
    def sources(
        self,
    ) -> tuple[VectorStore | StoreSnapshot | MultiVectorSource | Live[MultiVectorSource], ...]: ...
    @property
    def segments(self) -> tuple[Segment, ...]: ...
    @property
    def requires(self) -> dict[str, Representation]: ...
    @property
    def score_semantics(self) -> str: ...
    @property
    def feature(self) -> str: ...
    def rerank(
        self, query: Query, candidates: Sequence[Candidate], *, budget: ResourceBudget
    ) -> np.ndarray: ...

class StoreSnapshot:
    @property
    def segment(self) -> Segment: ...
    @property
    def format(self) -> str: ...
    @property
    def score_semantics(self) -> str: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def dimension(self) -> int: ...
    @property
    def document_count(self) -> int: ...
    @property
    def token_count(self) -> int: ...
    def document_lengths(self, document_ids: Sequence[int]) -> dict[int, int]: ...
    def fetch(
        self, document_ids: Sequence[int], *, threads: int | None = None
    ) -> tuple[np.ndarray, np.ndarray]: ...

class VectorStore:
    format: ClassVar[str]
    score_semantics: ClassVar[str]
    @property
    def path(self) -> Path: ...
    @property
    def representation(self) -> Representation: ...
    @property
    def dimension(self) -> int: ...
    @property
    def segment(self) -> Segment: ...
    def snapshot(self) -> StoreSnapshot: ...
    def append(
        self,
        document_ids: Iterable[str],
        embeddings: np.ndarray,
        document_lengths: np.ndarray,
        *,
        threads: int | None = None,
    ) -> StoreSnapshot: ...
    def delete(self, document_ids: Iterable[str]) -> StoreSnapshot: ...

class Float32VectorStore(VectorStore):
    def __init__(self, path: str | Path) -> None: ...
    @classmethod
    def create(
        cls,
        path: str | Path,
        segment: Segment,
        embeddings: np.ndarray,
        document_lengths: np.ndarray,
        representation: Representation,
        *,
        threads: int | None = None,
    ) -> Float32VectorStore: ...

class Int8VectorStore(VectorStore):
    def __init__(self, path: str | Path) -> None: ...
    @classmethod
    def create(
        cls,
        path: str | Path,
        segment: Segment,
        embeddings: np.ndarray,
        document_lengths: np.ndarray,
        representation: Representation,
        *,
        threads: int | None = None,
    ) -> Int8VectorStore: ...

def open_vector_store(path: str | Path) -> VectorStore: ...
def maxsim_scores_packed(
    query: np.ndarray,
    documents: np.ndarray,
    document_lengths: np.ndarray,
    *,
    max_batch_tokens: int | None = None,
    threads: int | None = None,
) -> np.ndarray: ...
def document_ids_digest(document_ids: Iterable[str]) -> str: ...
def _check_corpus_manifest(manifest: CorpusManifest) -> None: ...
def _check_representation(representation: Representation) -> None: ...
def _assert_corpora_compatible(left: CorpusManifest, right: CorpusManifest) -> None: ...
def _assert_representations_compatible(left: Representation, right: Representation) -> None: ...
